### ISSUE TITLE
Can this project be used outside of cyverse

### ISSUE THREAD

**Issue by technics3** [cyverse/sftpgo-deploy#1]
I'm trying to deploy an irods setup and serve files to the users via SFTP. 

This project seems to do what i want but i can't figure out how to use it. Even when everything is well configured the irods auth does not seems to work. 

Is this project supposed to be used outside of your environment ? If so, i'd love to have a chat with you about how to use it properly.

**Comment by iychoi** [comment]
Hi @technics3 

Yes, this project should work outside of cyverse. What was the issue?

**Comment by technics3** [comment]
Thank you for responding, 

The first problem is that even when i set variables in config.inc i get variables not set : 

```
WARN[0000] The "IRODS_SSL_ALGORITHM" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_SSL_SALT_SIZE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_AUTH_SCHEME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_SSL_HASH_ROUNDS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_CONF_HOST" variable is not set. Defaulting to a blank string. 
WARN[0000] The "WEBDAV_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_SSL_CA_CERT_PATH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_SSL_KEY_SIZE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "WEBDAV_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "WEBDAV_PORT" variable is not set. Defaulting to a blank string. 
no port specified: :<empty>
```

I tried and set those variables in the sftpgo dockerfile (via an .env file), that fixes the errors but even then sftpgo does not seems to talk with our irods server. I can't connect with any irods user and got an `invalid credentials` error.

One thing i just noticed : the irods_host variable is called `$IRODS_CONF_HOST` in the docker-compose but `$IRODS_HOST` in the config.inc so it was not passed to the final config. I changed that but still can't connect.  

Not that if i install drakkan sftpgo with irods-auth plugin the auth with our irods server works so i don't think the issue is our irods server (i may be wrong of course).

**Comment by iychoi** [comment]
Did you use `build` script file to build the cotainer image? And did you use `controller start` to start the container? Can you explain more in detail when the error occurs?

**Comment by technics3** [comment]
I built the image using the `build` script and i start / stop the container using the `controller` script.
All of that works, the container start and if i add the right variables in `config.inc` the sftpgo config is fine. Except that SFTPGo does not seems to connect to iRods even if the configuration seems ok.

**Comment by iychoi** [comment]
Have you checked the logs of both SFTPGo and auth-plugin? You can use `docker logs` to capture SFTPGo logs.  To get logs from sftpgo-auth-irods, you need to get into the container (`docker exec ...`) and find the log file located at `/tmp/`. 

You may have wrong configuration in `sftpgo.json`. After running the docker, ge into the container and double check if these fields have correct values.
1. Check `external_auth_hook`, here is the hint.
> https://github.com/cyverse/sftpgo-deploy/blob/main/sftpgo/scripts/sftpgo.json.template#L212
2. Check `commands` and `env`,
> https://github.com/cyverse/sftpgo-deploy/blob/main/sftpgo/scripts/sftpgo.json.template#L380

It will be more clear if you show me the sftpgo and sftpgo-auth-irods logs.

**Comment by technics3** [comment]
Thanks a lot for your time, this is extremely useful. 
I already checked the sftpgo.json config and it was indeed correct, but i haven't checked the irods_auth_plugin logs. It shows this everytime i try to connect : 

```
time="2024-02-01T15:51:42Z" level=error msg="envconfig.Process: assigning IRODS_SSL_KEY_SIZE to IRODSSSLKeySize: converting '' to type int. details: strconv.ParseInt: parsing \"\": invalid syntax"
```

My config.inc looks like this : 

```
#!/bin/bash

export ENV_NAME=cyverse_datastore_sftp

# SFTPGo setting
export SFTP_PORT=2022
export SFTPGO_ADMIN_UI_PORT=8080
export SFTPGO_VAULT="/srv/sftpgo"
export SFTPGO_HOME_PATH="$SFTPGO_VAULT/data"
export SFTPGO_ADMIN_USER="<USER>"
export SFTPGO_ADMIN_PASSWORD="<PASS>"
export SFTPGO_LOG_DIR="/var/log/sftpgo"
# iRODS Setting
export IRODS_AUTH_SCHEME="native"
export IRODS_PROXY_USER=""
export IRODS_PROXY_PASSWORD=""
export IRODS_HOST="<HOST_FQDN>"
export IRODS_PORT=1247
export IRODS_ZONE="<ZONE_NAME>"
export IRODS_SHARED="/<ZONE_NAME>/home"
export WEBDAV_PORT="8888"
```

I deleted everything SSL related on the docker compose and the sftpgo template, SFTPGo can now talk to the irods server !!!
It still doesn't work but now it seems to be a config problem on my side. I'll update the issue tomorrow when it works.

Thanks a lot for your very useful hints.

**Comment by iychoi** [comment]
Okay, it seems there's an issue with environment param parsing. I added some default values to not fail. Can you pull the new commits and try again?

**Comment by technics3** [comment]
The problem seems to be the same, i got a warning everytime i build : 

```
WARN[0000] The "IRODS_SSL_ALGORITHM" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_SSL_SALT_SIZE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_SSL_HASH_ROUNDS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_SSL_CA_CERT_PATH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "IRODS_SSL_KEY_SIZE" variable is not set. Defaulting to a blank string. 
```

**Comment by iychoi** [comment]
I was able to replicate the issue. Fixed the "variable not set" issue. Can you retry?

**Comment by technics3** [comment]
It's working now without the warning, thanks a lot. 

Now i got this error while connecting with a user, but i guess now this time i got to debug my irods config and all : 

```
time="2024-02-02T15:59:14Z" level=debug msg="Connecting to nte-irods-icat:1247" function=Connect package=connection struct=IRODSConnection
time="2024-02-02T15:59:14Z" level=debug msg="Start up connection without CS Negotiation" function=connectWithoutCSNegotiation package=connection struct=IRODSConnection
time="2024-02-02T15:59:14Z" level=debug msg="Logging in using native authentication method" function=loginNative package=connection struct=IRODSConnection
time="2024-02-02T15:59:14Z" level=debug msg="Disconnecting the connection" function=Disconnect package=connection struct=IRODSConnection
time="2024-02-02T15:59:14Z" level=info msg="Authenticated user 'omero' using password, creating a SFTPGoUser"
time="2024-02-02T15:59:14Z" level=debug msg="creating .ssh dir '/devZone/home/omero/.ssh'"
time="2024-02-02T15:59:14Z" level=debug msg="Connecting to nte-irods-icat:1247" function=Connect package=connection struct=IRODSConnection
time="2024-02-02T15:59:14Z" level=debug msg="Start up connection without CS Negotiation" function=connectWithoutCSNegotiation package=connection struct=IRODSConnection
time="2024-02-02T15:59:15Z" level=debug msg="Logging in using native authentication method" function=loginNative package=connection struct=IRODSConnection
time="2024-02-02T15:59:15Z" level=debug msg="Disconnecting the connection" function=Disconnect package=connection struct=IRODSConnection
time="2024-02-02T15:59:15Z" level=info msg="Authenticated user 'omero': {\n  \"status\": 1,\n  \"username\": \"omero\",\n  \"home_dir\": \"/srv/sftpgo/data/omero\",\n  \"virtual_folders\": [\n    {\n      \"name\": \"omero_home\",\n      \"description\": \"iRODS home\",\n      \"mapped_path\": \"/srv/sftpgo/data/omero/omero\",\n      \"virtual_path\": \"/omero\",\n      \"filesystem\": {\n        \"provider\": 7,\n        \"irodsconfig\": {\n          \"endpoint\": \"nte-irods-icat:1247\",\n          \"username\": \"omero\",\n          \"password\": {\n            \"status\": \"Plain\"\n          },\n          \"collection_path\": \"/devZone/home/omero\",\n          \"auth_scheme\": \"native\",\n          \"cs_negotiation_policy\": \"CS_NEG_DONT_CARE\",\n          \"ssl_key_size\": 32,\n          \"ssl_algorithm\": \"AES-256-CBC\",\n          \"ssl_salt_size\": 8,\n          \"ssl_hash_rounds\": 16\n        }\n      }\n    },\n    {\n      \"name\": \"omero_home\",\n      \"description\": \"iRODS home\",\n      \"mapped_path\": \"/srv/sftpgo/data/omero/home\",\n      \"virtual_path\": \"/home\",\n      \"filesystem\": {\n        \"provider\": 7,\n        \"irodsconfig\": {\n          \"endpoint\": \"nte-irods-icat:1247\",\n          \"username\": \"omero\",\n          \"password\": {\n            \"status\": \"Plain\"\n          },\n          \"collection_path\": \"/devZone/home\",\n          \"auth_scheme\": \"native\",\n          \"cs_negotiation_policy\": \"CS_NEG_DONT_CARE\",\n          \"ssl_key_size\": 32,\n          \"ssl_algorithm\": \"AES-256-CBC\",\n          \"ssl_salt_size\": 8,\n          \"ssl_hash_rounds\": 16\n        }\n      }\n    }\n  ],\n  \"permissions\": {\n    \"/\": [\n      \"list\"\n    ],\n    \"/home\": [\n      \"*\"\n    ],\n    \"/omero\": [\n      \"*\"\n    ]\n  },\n  \"filters\": {},\n  \"filesystem\": {\n    \"provider\": 0,\n    \"irodsconfig\": null\n  }\n}"
```

Update : the connection between sftpgo and the irods server works, sftpgo successfully create a .ssh dir on irods when i try to connect with a user. But i still get an "invalid credential" error and can't log in.

**Comment by technics3** [comment]
Just checking : have you had time to try and replicate this error ? 
Seems a bit odd that sftpgo can create a dir in iRods but still return an invalid credentials error.

**Comment by iychoi** [comment]
No, I don't have access to your iRODS so cannot replicate the issue.

The iRODS authentication module only checks iRODS access and returns json for creating SFTPGo filesystem. The json output in the log has wrong info, two identical virtual folders", "omero_home". This is because your `IRODS_SHARED` variable has wrong value. It should be a shared directory, often refers `/<zone>/home/public`, should 
not be `/<zone>/home`.

**Comment by technics3** [comment]
Sorry to bother you again, 

I did not understood the `IRODS_SHARE` variable, i changed it to use `/devZone/home/public` which exist on my irods install.

I still get the same `invalid credentials` error.  

Here is my config file : 

```
#!/bin/bash

export ENV_NAME=cyverse_datastore_sftp

# SFTPGo setting
export WEBDAV_PORT=8080
export SFTP_PORT=2022
export SFTPGO_ADMIN_UI_PORT=8888
export SFTPGO_VAULT="/srv/sftpgo"
export SFTPGO_HOME_PATH="$SFTPGO_VAULT/data"
export SFTPGO_ADMIN_USER="admin"
export SFTPGO_ADMIN_PASSWORD="<ADMIN_PASS>"
export SFTPGO_LOG_DIR="/var/log/sftpgo"
# iRODS Setting
export IRODS_PROXY_USER=""
export IRODS_PROXY_PASSWORD=""
export IRODS_HOST="<IRODS_ICAT_PRIVATE_IP>"
export IRODS_PORT=1247
export IRODS_ZONE="devZone"
export IRODS_AUTH_SCHEME="native"
export IRODS_SSL_CA_CERT_PATH=""
export IRODS_SSL_ALGORITHM="AES-256-CBC"
export IRODS_SSL_KEY_SIZE=32
export IRODS_SSL_SALT_SIZE=8
export IRODS_SSL_HASH_ROUNDS=16
export IRODS_SHARED="/devZone/home/public"
```

The Json SFTPGo creates : 

```json
'test': {
    "status": 1,
    "username": "test",
    "home_dir": "/srv/sftpgo/data/test",
    "virtual_folders": [
        {
        "name": "test_home",
        "description": "iRODS home",
        "mapped_path": "/srv/sftpgo/data/test/test",
        "virtual_path": "/test",
        "filesystem": {
            "provider": 7,
            "irodsconfig": {
                "endpoint": "<IRODS_ICAT_PRIVATE_IP>:1247",
                "username": "test",
                "password": {"status": "Plain"},
                "collection_path": "/devZone/home/test",
                "auth_scheme": "native",
                "cs_negotiation_policy": "CS_NEG_DONT_CARE",
                "ssl_key_size": 32,
                "ssl_algorithm": "AES-256-CBC",
                "ssl_salt_size": 8,
                "ssl_hash_rounds": 16
                }
            }
        },
        {
        "name": "test_public",
        "description": "iRODS public",
        "mapped_path": "/srv/sftpgo/data/test/public",
        "virtual_path": "/public",
        "filesystem": {
            "provider": 7,
            "irodsconfig": {
                "endpoint": "<IRODS_ICAT_PRIVATE_IP>:1247",
                "username": "test",
                "password": {
                    "status": "Plain"
                },
                "collection_path": "/devZone/home/public",
                "auth_scheme": "native",
                "cs_negotiation_policy": "CS_NEG_DONT_CARE",
                "ssl_key_size": 32,
                "ssl_algorithm": "AES-256-CBC",
                "ssl_salt_size": 8,
                "ssl_hash_rounds": 16
                }
            }
        }
    ],
    "permissions": {
                "/": ["list"],
                "/public": ["*"],
                "/test": ["*"]
            },
        "filters": {},
        "filesystem": { 
            "provider": 0,
            "irodsconfig": null
    }    
}"
```

If you got time and are interested on debugging this i can give you credentials to use our public iRods instance and try to replicate the issue. 

Again, thank you for your great help.

**Comment by iychoi** [comment]
The configuration created looks good. Maybe there's something else. Can you create a test account for the iRODS and share it with me via email (iychoi@arizona.edu)?

**Comment by technics3** [comment]
I'll let @glyg take care of i'll keep in touch with you via email for the follow up. 

Thanks a lot.

**Comment by iychoi** [comment]
There was a bug in `sftpgo-auth-irods` module when using native with non-proxy authentication. I fixed it now. Can you try it with new commit?

https://github.com/cyverse/sftpgo-deploy/commit/1d610cc735082470aa0dfa52b0c5e84b0b14953f

**Comment by technics3** [comment]
It is now working perfectly.
Thanks a lot for your help.

**Comment by iychoi** [comment]
No problem!
