### ISSUE TITLE
Add  IRODS_REQUIRE_CS_NEGOTIATION and IRODS_CS_NEGOTIATION_POLICY to sftpgo json template

### ISSUE THREAD

**Issue by technics3** [cyverse/sftpgo-deploy#2]
I need to use 

```
IRODS_REQUIRE_CS_NEGOTIATION="true"
IRODS_CS_NEGOTIATION_POLICY="CS_NEG_REQUIRE"
```

on my sftpgo config in order for PAM auth to work with my server. Those variables already exists on `sftpgo-auth-irods` so there is not much work to be done here.

I already done the necessary modification locally (added two lines in `sftpgo/scripts/sftpgo.json.template`, modified `sftpgo/scripts/prep-config-json.sh`, filled the variables in `config.inc` and `docker-compose.yml`),  i can share them with you if you want.

**Comment by iychoi** [comment]
Yes, please make a Pull-request for the changes. I'll merge them.

**Comment by technics3** [comment]
Thanks, i've open a pull request

**Comment by iychoi** [comment]
Merged. Thanks!
